site_name: GLPI

site_url: http://127.0.0.1:8000/

nav:
  - Home: index.md
  - Introdução: introducao.md
  - GLPI: GLPI.md
  - MKdocs: MKdocs.md
  - Conclusão: conclusao.md


theme:
  name: material
  palette:
    primary: green